### ISSUE TITLE
R-CarH3 cannot start domu

### ISSUE THREAD

**Issue by trungnc90** [xen-troops/meta-xt-prod-gen3-test#49]
hi,

I'm testing Xen 4.10 on board R-CarH3 2.0.

I attached the configuration files for domd and domu.

**In domd**, xl dmesg returned as below:
domd can be created ok (waylands can be started and executed demo apps)

_(XEN) avc:  denied  { physinfo } for domid=1 scontext=system_u:system_r:domU_t tcontext=system_u:system_r:xen_t tclass=xen
libxl: error: libxl.c:363:libxl_get_physinfo: getting physinfo: Permission denied
(XEN) avc:  denied  { readconsole } for domid=1 scontext=system_u:system_r:domU_t tcontext=system_u:system_r:xen_t tclass=xen
libxl: error: libxl_console.c:770:libxl_xen_console_read_line: reading console ring buffer: Permission denied_

**In domu**, log returned as below:

_[    0.443241]      device=eth0, hwaddr=08:00:27:ff:cb:ce, ipaddr=192.168.0.7, mask=255.255.255.0, gw=255.255.255.255
[    0.443260]      host=192.168.0.7, domain=, nis-domain=(none)
[    0.443273]      bootserver=255.255.255.255, rootserver=192.168.0.10, rootpath=
[    0.443397] ALSA device list:
[    0.443409]   No soundcards found.
[  318.431314] VFS: Unable to mount root fs via NFS, trying floppy.
[  318.431806] VFS: Cannot open root device "nfs" or unknown-block(2,0): error -6
[  318.431841] Please append a correct "root=" boot option; here are the available partitions:
[  318.431906] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(2,0)_

There's anyone facing this issue?
It seems backed end driver is not correct in domd, then domu will be failed when creation.

[domu.txt](https://github.com/xen-troops/meta-xt-prod-gen3-test/files/2007525/domu.txt)
[domd.txt](https://github.com/xen-troops/meta-xt-prod-gen3-test/files/2007526/domd.txt)

**Comment by otyshchenko1** [comment]
Hi, as I understand you are using NFS root for domd and domu, but with static IPs. Well, this configuration is supposed to be functional.

Could you attach the full "boot"(Xen + dom0) and "domd/domu" logs and the output of 'printenv' command from U-Boot command line.

BTW, Is "/tftpboot/xen_h3_v2.1/domu" dir properly added to "/etc/exports" file on your host machine?

**Comment by trungnc90** [comment]
hi otyshchenko1,

Currently, I could fix the issue related to nfs server.
Root cause is backend driver in domd couldn't start correctly because of lacking network configuration. When domd was started, it must run script (/xt/scripts/brigde-nfsroot.sh).

domu could execute now, but graphics driver still be failed.
_pvrsrvkm: unknown parameter 'EnableAPM' ignored
[   45.149763] [drm:pvr_drm_load [pvrsrvkm]] *ERROR* failed to create device node for device ffff800044c24410 (PVRSRV_ERROR_INVALID_DEVICE)_

Do you know how to fix this?
Thanks

**Comment by otyshchenko1** [comment]
Hi, glad to hear you could fix an issue. It would be really nice to see a pull request which contains a fix.

As for:
> domu could execute now, but graphics driver still be failed.
Normally this situation will not happen. Personally I haven't faced the issue when pvr_drm was failed to load. 

In order to help you I need a bit more info.
Could you attach the full "boot"(Xen + dom0) and "domd/domu" logs.
Also the "output" of the following commands after the system finishing booting, would be really helpfull:
- dom0: xenstore-ls -f | grep 'vdispl\|vgsx'
- domD: ps aux | grep displ_be
- domU: cat /proc/interrupts

Have you changed something in your setup comparing to the bare Gen3-test (tag v2.1), what exactly if so? What DDK binaries do you use?

**Comment by trungnc90** [comment]
hi,

Thank you for your support.

I updated some info as below:

**dom0**: xenstore-ls -f | grep 'vdispl|vgsx'

_root@generic-armv8-xt-dom0:~# xenstore-ls -f | grep 'vdispl|vgsx'_
_root@generic-armv8-xt-dom0:~#_

**domd**: ps aux | grep displ_be
_root@salvator-x-h3-xt-domd:~# ps aux | grep displ_be
 3023 root       0:00 /usr/bin/displ_be
 3139 root       0:00 {grep} /bin/busybox.nosuid /bin/grep displ_be_

**domu**: cat /proc/interrupts
_root@salvator-x-h3-xt-domu:~# cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3
  0:        474          0          0          0   xen-dyn Edge    -event     xenbus
  3:      38102       1092       1182       1307     GIC-0  27 Level     arch_timer
  4:      19907          1          1          1     GIC-0  31 Level     events
  5:        399          0          0          0   xen-dyn Edge    -event     hvc_console
  6:          0          0          0          0   xen-dyn Edge    -event     vdispl
  7:          0          0          0          0   xen-dyn Edge    -event     vdispl
  8:          5          0          0          0   xen-dyn Edge    -event     eth0-q0-tx
  9:       3099          0          0          0   xen-dyn Edge    -event     eth0-q0-rx
 10:          9          0          0          0   xen-dyn Edge    -event     eth0-q1-tx
 11:         28          0          0          0   xen-dyn Edge    -event     eth0-q1-rx
 12:       7982          0          0          0   xen-dyn Edge    -event     eth0-q2-tx
 13:       8342          0          0          0   xen-dyn Edge    -event     eth0-q2-rx
 14:         37          0          0          0   xen-dyn Edge    -event     eth0-q3-tx
 15:        123          0          0          0   xen-dyn Edge    -event     eth0-q3-rx
 16:          0          0          0          0   xen-dyn Edge    -event     vkbd
IPI0:      1157       3081       3024       4074       Rescheduling interrupts
IPI1:       123         30        146        123       Function call interrupts
IPI2:         0          0          0          0       CPU stop interrupts
IPI3:         0          0          0          0       Timer broadcast interrupts
IPI4:         0          0          0          0       IRQ work interrupts
IPI5:         0          0          0          0       CPU wake-up interrupts_

I also attached dmesg log for 3 domains.
[domu_dmesg.txt](https://github.com/xen-troops/meta-xt-prod-gen3-test/files/2015417/domu_dmesg.txt)
[dom0_dmesg.txt](https://github.com/xen-troops/meta-xt-prod-gen3-test/files/2015418/dom0_dmesg.txt)
[domd_dmesg.txt](https://github.com/xen-troops/meta-xt-prod-gen3-test/files/2015419/domd_dmesg.txt)

> Have you changed something in your setup comparing to the bare Gen3-test (tag v2.1), what exactly if so? What DDK binaries do you use?

I only followed the installation guide from Xentroop project.
https://github.com/xen-troops/meta-xt-prod-gen3-test/blob/master/INSTALL

Regarding binary file, I got them from EPAM:
_rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz
rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz_

But in 6th step, they use:
_r8a7795-rcar-proprietary-graphic.tar.gz_

Then, I took the file **rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz** and renamed to **r8a7795-rcar-proprietary-graphic.tar.gz**.

Probably this step is the reason why graphics driver couldn't work correctly in domu side.

Thanks

**Comment by otyshchenko1** [comment]
Hi.

The 6th step of INSTALL is outdated. We should have updated it. Sorry for hitting on that.

> Probably this step is the reason why graphics driver couldn't work correctly in domu side.
Likely yes.
All what you need is just to put both binary archives as is, without renaming.
rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz
rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz

**Comment by pranaykukreti** [comment]
Hi,
Is there no support for m3ulcb? 

rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz
rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz
where can i download these drivers from?

**Comment by otyshchenko1** [comment]
Hi, pranaykukreti.
There is no support for m3ulcb so far. We are about to adding h3ulcb support. 
I believe that:
rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz
rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz
would be appropriate for h3ulcb as well since H3 SoC is the same.

You can't download these binaries, since they are not available at public location. Please contact Renesas.

**Comment by trungnc90** [comment]
hi,

Thank you for your support.

I have tried 2 ways:
1. Following your guide:
Last time, I put both (**rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz + rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz**) and **r8a7795-rcar-proprietary-graphic.tar.gz** (renamed from  rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz)

2. Replace binary to rootfs of domd and domu
I got the binary (rcar-proprietary-graphic-salvator-x-h3-xt-domd.tar.gz + rcar-proprietary-graphic-salvator-x-h3-xt-domu.tar.gz) and replaced to rootfs of domd and domu.

2 ways returned the same error: cannot start graphics driver in domu.

Can you check the log I attached in previous comment?
Can you find root cause for this?

Thanks.

**Comment by otyshchenko1** [comment]
Hi,

The correct way is just to put both archives:
rcar-proprietary-graphic-MACHINE-NAME-xt-domd.tar.gz
rcar-proprietary-graphic-MACHINE-NAME-xt-domu.tar.gz

Looking at domd log you provided, I got an impression that you had used outdated DDK binaries somehow.

Your PVRKM log says the following:
[    8.841129] vgsx:(VMMCreatePvzConnection:313): Creating Xen PVZ connection
[    8.841167] vgsx:(gsx_back_init:698): Initializing backend driver

While my PVRKM log says next:
[   14.780740] vgsx:(VMMCreatePvzConnection:313): Creating Xen PVZ connection
[   14.780778] vgsx:(gsx_back_init:829): Initializing backend driver

The diff is in the line of code from what printk is being called. And in your case which is "gsx_back_init:698" it corresponds to PVRKM for Gen3-test (tag v2.0), but not for (tag v2.1).
Could you please double check on your side.

**Comment by otyshchenko1** [comment]
I have already checked again and it works as expected.

This is the PVRKM log in domd:
[    6.272644] vgsx:(VMMCreatePvzConnection:313): Creating Xen PVZ connection
[    6.272692] vgsx:(gsx_back_init:829): Initializing backend driver
[    6.283726] pvrsrvkm fd000000.gsx: opp[1/4]: (200000000 Hz, 830000 uV)
[    6.283778] pvrsrvkm fd000000.gsx: opp[2/4]: (300000000 Hz, 830000 uV)
[    6.283800] pvrsrvkm fd000000.gsx: opp[3/4]: (400000000 Hz, 830000 uV)
[    6.283821] pvrsrvkm fd000000.gsx: opp[4/4]: (600000000 Hz, 830000 uV)
[    6.283851] DVFS : Changed GPU clock to 600000000 [Hz]
[    6.289120] [drm] Initialized pvr 1.9.4908383 20110701 on minor 2

This is the PVRKM log in domu:
[    5.879456] vgsx:(VMMCreatePvzConnection:313): Creating Xen PVZ connection
[    5.879496] vgsx:(gsx_front_init:565): Initializing frontend driver
[    5.989775] PVR_K:  1915: RGXGetBVNCConfig: Reverting to compile time BVNC 4.46.6.62
[    5.990713] [drm] Initialized pvr 1.9.4908383 20110701 on minor 1

**Comment by otyshchenko1** [comment]
Hi, trungnc90,

Did you manage to get graphic driver functional in DomU?

**Comment by trungnc90** [comment]
hi,

> Did you manage to get graphic driver functional in DomU?

What do you mean?

 I only run the script (brigde-nfs.sh) in domd. Do i need to do any more before starting domu?

**Comment by trungnc90** [comment]
hi,

graphic driver in domu still doesn't work.

Do you think I got wrong binaries?

**Comment by otyshchenko1** [comment]
Hi,

> Do you think I got wrong binaries?
Yes, it turned out to be a reason.

**Comment by trungnc90** [comment]
Hi,

I got new binaries, and it could work well.

Thank you for your support.
